import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/Nav";
import AuthProvider from "./(components)/AuthProvider";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "./(components)/Footer";
import Query from "@/react-query/reactquery";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "HostelBazzar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Query>
            
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>

          <Nav />
          {children}
          
          <Footer/>
          </ThemeProvider>
          </Query>
        </AuthProvider>
      </body>
    </html>
  );
}
